#FROM registry.redhat.io/rhel7.6
FROM registry.redhat.io/ubi7-init 

#RUN mkdir -p rhel

#COPY rhel/* rhel/
#COPY rhel.iso rhel.iso

RUN yum-config-manager --add-repo http://172.29.166.235:8080/rhel7/c31
RUN echo "gpgcheck=0" >> /etc/yum.repos.d/172.29.166.235_8080_rhel7_c31.repo
#RUN yum-config-manager --add-repo http://172.19.85.40:80/rhel7/c31
#RUN echo "gpgcheck=0" >> /etc/yum.repos.d/172.19.85.40_80_rhel7_c31.repo
RUN yum -y install at && \
   yum -y install bind && \
   yum -y install bind-chroot && \
   yum -y install bind-libs && \
   yum -y install bind-utils && \
   yum -y install atop && \
   yum -y install audit-libs-python && \
   yum -y install autofs && \
   yum -y install autogen-libopts && \
   yum -y install bc && \
   yum -y install bzip2 && \
   yum -y install bzip2-libs && \
   yum -y install c3release && \
   yum -y install checkpolicy && \
   yum -y install cloud-init && \
   yum -y install crash && \
   yum -y install dejavu-fonts-common && \
   yum -y install dejavu-sans-mono-fonts && \
   yum -y install dstat && \
   yum -y install ed && \
   yum -y install expect && \
   yum -y install expectk && \
   yum -y install flashupdt && \
   yum -y install fontconfig && \
   yum -y install fontpackages-filesystem && \
   yum -y install freeipmi && \
   yum -y install freeipmi-bmc-watchdog && \
   yum -y install freeipmi-ipmidetectd && \
   yum -y install ftp && \
   yum -y install gdb && \
   yum -y install gdbm-devel && \
   yum -y install glances && \
   yum -y install glibc && \
   yum -y install glibc.i686 && \
   yum -y install glibc-devel && \
   yum -y install glibc-headers && \
   yum -y install gpm-libs && \
   yum -y install gssproxy && \
   yum -y install hesiod && \
   yum -y install htop && \
   yum -y install iftop && \
   yum -y install iotop && \
   yum -y install ipmitool && \
   yum -y install ipmiutil && \
   yum -y install java-1.8.0-openjdk && \
   yum -y install java-1.8.0-openjdk-devel && \
   yum -y install jemalloc && \
   yum -y install kernel-headers && \
   yum -y install kernel-tools && \
   yum -y install keyutils && \
   yum -y install ksh && \
   yum -y install libbasicobjects && \
   yum -y install libcgroup && \
   yum -y install libcollection && \
   yum -y install libdb-devel && \
   yum -y install liberation-fonts-common && \
   yum -y install liberation-mono-fonts && \
   yum -y install libevent && \
   yum -y install libgcc && \
   yum -y install libgcc.i686 && \
   yum -y install libICE && \
   yum -y install libini_config && \
   yum -y install libmicrohttpd && \
   yum -y install libnfsidmap && \
   yum -y install libpath_utils && \
   yum -y install libpcap && \
   yum -y install libref_array && \
   yum -y install libreport-filesystem && \
   yum -y install libsemanage-python && \
   yum -y install libstdc++ && \
   yum -y install libstdc++.i686 && \
   yum -y install libSM && \
   yum -y install libtalloc && \
   yum -y install libtevent && \
   yum -y install libtirpc && \
   yum -y install libverto-tevent && \
   yum -y install libX11 && \
   yum -y install libX11-common && \
   yum -y install libXau && \
   yum -y install libXaw && \
   yum -y install libxcb && \
   yum -y install libXext && \
   yum -y install libXft && \
   yum -y install libXmu && \
   yum -y install libXpm && \
   yum -y install libXrender && \
   yum -y install libXt && \
   yum -y install libyaml && \
   yum -y install lm_sensors-libs && \
   yum -y install lshw && \
   yum -y install lsof && \
   yum -y install mailcap && \
   yum -y install mailx && \
   yum -y install man-pages && \
   yum -y install man-pages-overrides && \
   yum -y install mariadb-libs && \
   yum -y install mcelog && \
   yum -y install mdadm && \
   yum -y install microcode_ctl && \
   yum -y install mtools && \
   yum -y install mtr && \
   yum -y install multitail && \
   yum -y install ncurses-libs && \
   yum -y install ncurses-libs.i686 && \
   yum -y install net-snmp && \
   yum -y install net-snmp-agent-libs && \
   yum -y install net-snmp-libs && \
   yum -y install net-snmp-utils && \
   yum -y install net-tools && \
   yum -y install nfs-utils && \
   yum -y install nmap && \
   yum -y install nmap-ncat && \
   yum -y install nss-softokn-freebl && \
   yum -y install nss-softokn-freebl.i686 && \
   yum -y install ntp && \
   yum -y install ntpdate && \
   yum -y install numactl && \
   yum -y install numad && \
   yum -y install openssl-libs && \
   yum -y install openssh && \
   yum -y install openssh-server && \
   yum -y install openssh-clients && \
   yum -y install OpenIPMI && \
   yum -y install OpenIPMI-libs && \
   yum -y install OpenIPMI-modalias && \
   yum -y install pam_radius && \
   yum -y install parted && \
   yum -y install pciutils && \
   yum -y install perl && \
   yum -y install perl-Archive-Extract && \
   yum -y install perl-Archive-Tar && \
   yum -y install perl-autodie && \
   yum -y install perl-B-Lint && \
   yum -y install perl-Business-ISBN && \
   yum -y install perl-Business-ISBN-Data && \
   yum -y install perl-Carp && \
   yum -y install perl-CGI && \
   yum -y install perl-Compress-Raw-Bzip2 && \
   yum -y install perl-Compress-Raw-Zlib && \
   yum -y install perl-constant && \
   yum -y install perl-core && \
   yum -y install perl-CPAN && \
   yum -y install perl-CPAN-Meta && \
   yum -y install perl-CPAN-Meta-Requirements && \
   yum -y install perl-CPAN-Meta-YAML && \
   yum -y install perl-CPANPLUS && \
   yum -y install perl-CPANPLUS-Dist-Build && \
   yum -y install perl-Crypt-SSLeay && \
   yum -y install perl-Data-Dumper && \
   yum -y install perl-DBD-SQLite && \
   yum -y install perl-DB_File && \
   yum -y install perl-DBI && \
   yum -y install perl-DBIx-Simple && \
   yum -y install perl-devel && \
   yum -y install perl-Digest && \
   yum -y install perl-Digest-MD5 && \
   yum -y install perl-Digest-SHA && \
   yum -y install perl-Encode && \
   yum -y install perl-Encode-Locale && \
   yum -y install perl-Env && \
   yum -y install perl-Exporter && \
   yum -y install perl-ExtUtils-CBuilder && \
   yum -y install perl-ExtUtils-Embed && \
   yum -y install perl-ExtUtils-Install && \
   yum -y install perl-ExtUtils-MakeMaker && \
   yum -y install perl-ExtUtils-Manifest && \
   yum -y install perl-ExtUtils-ParseXS && \
   yum -y install perl-FCGI && \
   yum -y install perl-File-CheckTree && \
   yum -y install perl-File-Fetch && \
   yum -y install perl-File-Listing && \
   yum -y install perl-File-Path && \
   yum -y install perl-File-Temp && \
   yum -y install perl-Filter && \
   yum -y install perl-Font-AFM && \
   yum -y install perl-Getopt-Long && \
   yum -y install perl-HTML-Format && \
   yum -y install perl-HTML-Parser && \
   yum -y install perl-HTML-Tagset.noarch && \
   yum -y install perl-HTML-Tree && \
   yum -y install perl-HTTP-Cookies && \
   yum -y install perl-HTTP-Daemon && \
   yum -y install perl-HTTP-Date && \
   yum -y install perl-HTTP-Message && \
   yum -y install perl-HTTP-Negotiate && \
   yum -y install perl-HTTP-Tiny && \
   yum -y install perl-IO-Compress-Base && \
   yum -y install perl-IO-Compress-Bzip2 && \
   yum -y install perl-IO-Compress-Zlib && \
   yum -y install perl-IO-HTML && \
   yum -y install perl-IO-Socket-IP && \
   yum -y install perl-IO-Socket-SSL && \
   yum -y install perl-IO-Socket-Timeout && \
   yum -y install perl-IO-stringy && \
   yum -y install perl-IO-Zlib && \
   yum -y install perl-IPC-Cmd && \
   yum -y install perl-JSON && \
   yum -y install perl-JSON-PP && \
   yum -y install perl-libs && \
   yum -y install perl-libwww-perl.noarch && \
   yum -y install perl-libxml-perl.noarch && \
   yum -y install perl-Locale-Codes && \
   yum -y install perl-Locale-Maketext && \
   yum -y install perl-Locale-Maketext-Simple && \
   yum -y install perl-local-lib && \
   yum -y install perl-Log-Message && \
   yum -y install perl-Log-Message-Simple && \
   yum -y install perl-LWP-MediaTypes && \
   yum -y install perl-macros && \
   yum -y install perl-Module-Build && \
   yum -y install perl-Module-CoreList && \
   yum -y install perl-Module-Load && \
   yum -y install perl-Module-Load-Conditional && \
   yum -y install perl-Module-Loaded && \
   yum -y install perl-Module-Metadata && \
   yum -y install perl-Module-Pluggable && \
   yum -y install perl-Net-Daemon && \
   yum -y install perl-Net-HTTP && \
   yum -y install perl-Net-LibIDN && \
   yum -y install perl-Net-SSLeay && \
   yum -y install perl-Object-Accessor && \
   yum -y install perl-Package-Constants && \
   yum -y install perl-Params-Check && \
   yum -y install perl-parent && \
   yum -y install perl-Parse-CPAN-Meta && \
   yum -y install perl-PathTools && \
   yum -y install perl-PerlIO-via-Timeout && \
   yum -y install perl-Perl-OSType && \
   yum -y install perl-PlRPC && \
   yum -y install perl-Pod-Checker && \
   yum -y install perl-Pod-Escapes && \
   yum -y install perl-Pod-LaTeX && \
   yum -y install perl-podlators && \
   yum -y install perl-Pod-Parser && \
   yum -y install perl-Pod-Perldoc && \
   yum -y install perl-Pod-Simple && \
   yum -y install perl-Pod-Usage && \
   yum -y install perl-Redis && \
   yum -y install perl-Scalar-List-Utils && \
   yum -y install perl-SNMP_Session && \
   yum -y install perl-Socket && \
   yum -y install perl-Storable && \
   yum -y install perl-String-CRC32 && \
   yum -y install perl-Sys-Syslog && \
   yum -y install perl-Term-UI && \
   yum -y install perl-Test-Harness && \
   yum -y install perl-Test-Simple && \
   yum -y install perl-Text-ParseWords && \
   yum -y install perl-Text-Soundex && \
   yum -y install perl-Text-Unidecode && \
   yum -y install perl-Thread-Queue && \
   yum -y install perl-threads && \
   yum -y install perl-threads-shared && \
   yum -y install perl-TimeDate && \
   yum -y install perl-Time-HiRes && \
   yum -y install perl-Time-Local && \
   yum -y install perl-Time-Piece && \
   yum -y install perl-Try-Tiny && \
   yum -y install perl-URI.noarch && \
   yum -y install perl-version && \
   yum -y install perl-Version-Requirements && \
   yum -y install perl-WWW-RobotRules && \
   yum -y install perl-XML-Dumper.noarch && \
   yum -y install perl-XML-Grove.noarch && \
   yum -y install perl-XML-Parser && \
   yum -y install perl-XML-Twig.noarch && \
   yum -y install policycoreutils-python && \
   yum -y install postfix && \
   yum -y install psmisc && \
   yum -y install pyparsing && \
   yum -y install python2-psutil && \
   yum -y install python-backports && \
   yum -y install python-backports-ssl_match_hostname && \
   yum -y install python-chardet && \
   yum -y install python-IPy && \
   yum -y install python-jsonpatch && \
   yum -y install python-jsonpointer && \
   yum -y install python-kitchen && \
   yum -y install python-prettytable && \
   yum -y install python-requests && \
   yum -y install python-six && \
   yum -y install python-urllib3 && \
   yum -y install PyYAML && \
   yum -y install quota && \
   yum -y install quota-nls && \
   yum -y install redis && \
   yum -y install rpcbind && \
   yum -y install rsync && \
   yum -y install setools-libs && \
   yum -y install smartmontools && \
   yum -y install sos && \
   yum -y install strace && \
   yum -y install syscfg && \
   yum -y install syslinux && \
   yum -y install syslinux-extlinux && \
   yum -y install sysstat && \
   yum -y install systemtap-sdt-devel && \
   yum -y install tcl && \
   yum -y install tcpdump && \
   yum -y install tcp_wrappers && \
   yum -y install tcsh && \
   yum -y install telnet && \
   yum -y install tftp && \
   yum -y install tk && \
   yum -y install traceroute && \
   yum -y install unzip && \
   yum -y install vim-common && \
   yum -y install vim-enhanced && \
   yum -y install vim-filesystem && \
   yum -y install watchdog && \
   yum -y install wget && \
   yum -y install wireshark-gnome && \
   yum -y install xfsprogs && \
   yum -y install xorg-x11-xauth && \
   yum -y install xterm && \
   yum -y install ypbind && \
   yum -y install yp-tools && \
   yum -y install yum-utils && \
   yum -y install zip && \
   yum -y install zsh && \
   yum -y install less 

RUN echo "kernel.sem=1024    32000   100     100" >> /etc/sysctl.conf
RUN echo "b1gd0g" > /tmp/pd; echo "b1gd0g" >> /tmp/pd ; cat /tmp/pd | passwd 


CMD ["/sbin/init"]

